### PR TITLE
Add autoMirroded attribute to some icons so that they render correctly on Rtl mode.

### PR DESCRIPTION
**Pull request by bmarty**
This should fix the issues on icons reported here: https://github.com/element-hq/element-x-android/issues/2865

There is maybe a way to add this attribute to the Figma source of truth (CC @amshakal), but waiting for it this should do the trick.

Here is a side by side comparison of the icons:

image

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
This icon looks kind of broken 😅 :

image

Other than that, great job, it's a nice workaround!

**Comment by bmarty** [comment]
> This icon looks kind of broken 😅 :
> image
> 
> Other than that, great job, it's a nice workaround!

I think it's fine and match what is expected by people using RTL mode. See this other icons:

image

There are still some work to do on the design side, since I cannot autoMirroded this ones for instance:

image
image

Also I am not sure if I can autoMirrored this ones with question mark:

imageimage

I think I should, but maybe @IbraChan can help (sorry to ping you directly, but since you open https://github.com/element-hq/element-x-android/issues/3510 I think that you want to help!)

**Comment by jmartinesp** [comment]
I'd say it still looks weird to me, also the check icon is not [in the list of automirrored material icons](https://developer.android.com/reference/kotlin/androidx/compose/material/icons/Icons.AutoMirrored.Outlined).

In any case, it's not a blocker I think.

**Comment by bmarty** [comment]
The list of icons in your link is not exhaustive (there are extensions with more icons.). I have found https://developers.google.com/fonts/docs/material_icons#which_icons_should_be_mirrored_for_rtl which is interesting.

So it seems that's you're right about the check icon. I will revert the auto-mirroring on the checks, and add it to the question mark, like:
image, image and image

**Comment by IbraChan** [comment]
I believe that many icons, in fact, most of them, don’t need to be mirrored. Only those containing some kind of an arrow (left or right) should be mirrored. Additionally, mirroring some icons might make them look broken. For example, icons containing a check mark (as jmartinesp mentioned), and the Italic and Bold icons. Some icons, like the room (hashtag) icon, conventionally look the way they are regardless of the writing system. For icons that contain a question mark, the form of the question mark in the icons is common (and people don't find it strange) in systems that write from left to right, or at least the lanaguage i speak which is Arabic, with another mirrored version “؟”. However, the original form is common, and not mirroring it won’t make it look strange to the user.

To enhance testing, I have begun contributing to the application’s translation and aim to complete it shortly. ^^

**Comment by bmarty** [comment]
Thanks for the input @IbraChan . Let's merge the PR and see if we need to revisit later.
Note that all the icons are not used in the final application, so if a used icon is too strange in RTL in the final application we will change the icon.

**Pull request merged**
